// Morocco cities
const cities = [
  "Agadir",
  "Ahfir",
  "Akhfennir",
  "Al Fqih BenSalah",
  "Arfoud",
  "Asilah",
  "Azemmour",
  "Aïn Beni Mathar",
  "Aïn Leuh",
  "Berkane",
  "Bni Bouayach",
  "Bouarfa",
  "Boujniba",
  "Bouznika",
  "Cap Negro II",
  "Casablanca",
  "Chefchaouene",
  "Dakhla",
  "El Aïoun",
  "El Hajeb",
  "El Jadid",
  "Errachidia",
  "Figuig",
  "Fnidek",
  "Fès",
  "Fès al Bali",
  "Gleibet El Foula",
  "Guelmim",
  "Gueltat Zemmour",
  "Ifrane",
  "Imlili",
  "Imzouren",
  "Jerada",
  "Kasba Tadla",
  "Kelaat Mgouna",
  "Kenitra",
  "Khemisset",
  "Khenifra",
  "Khouribga",
  "Ksar El Kebir",
  "Larache",
  "Mahroun",
  "Marrakesh",
  "Martil",
  "Marzouga",
  "Meknès",
  "Mhamid",
  "Midar",
  "Mnoud",
  "Mohammedia",
  "Nador",
  "Oualidia",
  "Ouarzazat",
  "Ouezzane",
  "Oujda-Angad",
  "Oukaïmedene",
  "Oulad Tayeb",
  "Oulad Teïma",
  "Ouled Khlifa",
  "Oulmes",
  "Rabat",
  "Reçani",
  "Safi",
  "Saidia",
  "Sale",
  "Sefrou",
  "Settat",
  "Setti Fatma",
  "Sidi Bennour",
  "Sidi Bouiachi",
  "Sidi Ifni",
  "Sidi Qacem",
  "Sidi Smai’il",
  "Skhirate",
  "Tafraout",
  "Taghazout",
  "Tagzout",
  "Tahla",
  "Tan-Tan",
  "Tangier",
  "Taounate",
  "Tarfaya",
  "Targuist",
  "Taroudant",
  "Taza",
  "Temara",
  "Tiflet",
  "Tirhanimîne",
  "Tiznit",
  "Tmourghout",
  "Torord",
  "Tétouan",
  "Youssoufia",
  "Zag",
  "Zagora",
  "Zaïo",
];
module.exports = cities;
